model:
  type: 'vit3d'  # Model type
  num_labels: 3  # Number of classes (AD, CN, MCI)
  freeze_layers: true
  input_size: 224
  patch_size: 16
  dropout_rate: 0.1

dataset:
  path: './adni'
  batch_size: 32
  val_ratio: 0.15
  test_ratio: 0.15
  input_size: 224
  preprocessing:
    voxel_spacing: [1.5, 1.5, 1.5]
    orientation: 'RAS'
    intensity_norm: true
    foreground_crop: true
    crop_margin: 10

training:
  epochs: 100
  device: 'cuda'
  seed: 42
  learning_rate: 0.001
  optimizer:
    type: 'adamw'
    weight_decay: 0.01
  scheduler:
    type: 'cosine'
    warmup_epochs: 5