# Model configuration
model:
  type: 'vit3d'  # Keep this as vit3d for compatibility
  num_labels: 3
  freeze_layers: true
  input_size: 224
  patch_size: 16  # Added this for the new architecture
  dropout_rate: 0.1
  architecture:
    hidden_size: 768
    num_attention_heads: 12
    intermediate_size: 3072
    pretrained_model: 'google/vit-base-patch16-224-in21k'
    freeze_last_n_layers: 4
    medical_preprocessing:
      enable: true
      kernel_sizes: [7, 5, 1]
      channels: [16, 32, 3]

# Dataset configuration
dataset:
  path: './adni'
  batch_size: 16  # Increased batch size
  val_ratio: 0.15
  test_ratio: 0.15
  input_size: 224
  preprocessing:
    voxel_spacing: [1.5, 1.5, 1.5]
    orientation: 'RAS'
    intensity_norm: true
    foreground_crop: true
    crop_margin: 10
    medical_augmentation:
      enable: true
      rotation_range: [-10, 10]
      scale_range: [0.95, 1.05]
      intensity_shift: [-0.1, 0.1]
      gamma_range: [0.9, 1.1]

# Training configuration
training:
  epochs: 50
  device: 'cuda'  # will fall back to CPU if not available
  seed: 42
  learning_rate: 0.0001
  optimizer:
    type: 'adamw'
    weight_decay: 0.01
    layer_specific_lrs:  # Different learning rates for different components
      vit_backbone: 0.00001
      medical_preprocessing: 0.0001
      feature_enhance: 0.0001
      classifier: 0.0001
  scheduler:
    type: 'cosine'
    T_0: 5
    warmup_epochs: 2
    min_lr: 1.0e-6
  early_stopping:
    enable: true
    patience: 10
    min_delta: 0.001
  loss:
    type: 'cross_entropy'
    label_smoothing: 0.1

# Paths configuration
paths:
  output_dir: './output'
  log_dir: './logs'
  checkpoint_dir: './checkpoints'
  data:
    raw: './adni/raw'
    processed: './adni/processed'
    metadata: './metadata/adni.csv'

# Logging configuration
logging:
  level: 'INFO'
  save_to_file: true
  log_frequency: 10

# Memory management for large medical images
memory:
  clear_cache_frequency: 1
  pin_memory: false  # For CPU training
  num_workers: 0     # For CPU training
  prefetch_factor: 2