# Model configuration
model:
  type: 'vit2d'
  num_labels: 3
  freeze_layers: true
  input_size: 224
  patch_size: 16
  dropout_rate: 0.1

  # Model specific settings
  vit2d:
    pretrained: 'google/vit-base-patch16-224-in21k'
    hidden_size: 768
    intermediate_size: 3072
    num_attention_heads: 12

  vit3d:
    pretrained: 'google/vit-base-patch16-224-in21k'
    hidden_size: 768
    use_memory_efficient: true

  cnn3d:
    pretrained: true
    base_channels: 64
    num_blocks: [3, 4, 6, 3]

# Dataset configuration
dataset:
  path: './adni'
  batch_size: 16
  val_ratio: 0.15
  test_ratio: 0.15
  input_size: 224
  preprocessing:
    voxel_spacing: [1.5, 1.5, 1.5]
    orientation: 'RAS'
    intensity_norm: true
    foreground_crop: true
    crop_margin: 10
    slice_selection:
      method: 'center'  # or 'average'
      num_slices: 5
    augmentation:
      enable: true
      rotation_range: [-10, 10]
      flip_probability: 0.5
      intensity_shift: [-0.1, 0.1]

# Training configuration
training:
  epochs: 50
  device: 'cuda'  # will fall back to CPU
  seed: 42
  learning_rate: 0.0001
  optimizer:
    type: 'adamw'
    weight_decay: 0.01
    layer_specific_lrs:
      pretrained: 0.00001
      new: 0.0001
  scheduler:
    type: 'cosine'
    T_0: 10  # Added for cosine annealing
    T_mult: 2
    eta_min: 1e-6
    warmup_epochs: 2
  early_stopping:
    patience: 10
    min_delta: 0.001
  gradient_clipping:
    enable: true
    max_norm: 1.0
  mixed_precision: false

# Paths configuration
paths:
  output_dir: './output'
  log_dir: './logs'
  checkpoint_dir: './checkpoints'
  data:
    raw: './adni/raw'
    processed: './adni/processed'
    metadata: './metadata/adni.csv'

# Logging configuration
logging:
  level: 'INFO'
  save_to_file: true
  log_frequency: 10