# config.yaml

model:
  type: 'vit3d'  # Options: '2d_vit', '3d_vit', '3d_cnn'
  num_labels: 3
  freeze_layers: true
  input_size: 224
  patch_size: 16   # Options: 8, 16, 32

dataset:
  path: './adni'
  batch_size: 32
  val_ratio: 0.15
  test_ratio: 0.15
  input_size: 224  # Should match model input_size

training:
  max_epochs: 100
  learning_rate: 0.001
  device: 'cuda'
  seed: 42
  amp: true
  tensorboard_log_dir: './logs/tensorboard'
  checkpoint_dir: './checkpoints'
  lr_scheduler:
    factor: 0.1
    patience: 10
  early_stopping:
    patience: 15
    min_delta: 0.001

# Add this section
paths:
  log_dir: './logs'
  output_dir: './output'
  checkpoint_dir: './checkpoints'
  tensorboard_dir: './logs/tensorboard'