# Model Configurations
model:
  # Shared settings
  num_labels: 3
  input_size: 224
  dropout_rate: 0.1
  freeze_layers: true

  # Model specific settings
  vit3d:
    type: 'vit3d'
    patch_sizes: [8, 16, 32]  # Different patch sizes to try
    pretrained: 'google/vit-base-patch16-224-in21k'

  vit2d:
    type: 'vit2d'
    patch_sizes: [8, 16, 32]
    pretrained: 'google/vit-base-patch16-224-in21k'
    slice_mode: 'center'  # or 'average'

  cnn3d:
    type: 'cnn3d'
    patch_sizes: [8, 16, 32]
    pretrained: 'resnet50'  # Will use inflated ResNet
    channels: [64, 128, 256, 512]

# Dataset configuration
dataset:
  path: './adni'
  batch_size: 8
  val_ratio: 0.15
  test_ratio: 0.15
  preprocessing:
    voxel_spacing: [1.5, 1.5, 1.5]
    orientation: 'RAS'
    intensity_norm: true
    foreground_crop: true
    crop_margin: 10
    # 2D specific
    slice_selection:
      method: 'center'  # or 'average'
      num_slices: 5
    # Data augmentation
    augmentation:
      enable: true
      rotation_range: [-10, 10]
      flip_probability: 0.5
      intensity_shift: [-0.1, 0.1]

# Training configuration
training:
  epochs: 50
  device: 'cuda'  # will fall back to CPU
  seed: 42
  base_learning_rate: 0.0001
  layer_specific_lrs:
    pretrained: 0.00001
    new: 0.0001
  optimizer:
    type: 'adamw'
    weight_decay: 0.01
  scheduler:
    type: 'cosine'
    warmup_epochs: 2
    min_lr: 1.0e-6
  early_stopping:
    patience: 10
    min_delta: 0.001

# Experiment tracking
experiment:
  name: 'alzheimer_detection_comparison'
  models_to_run: ['vit3d', 'vit2d', 'cnn3d']
  metrics:
    - accuracy
    - precision
    - recall
    - f1
    - confusion_matrix
  save_predictions: true
  save_model: true
  plot_results: true

# Paths and logging
paths:
  output_dir: './output'
  log_dir: './logs'
  checkpoint_dir: './checkpoints'
  results_dir: './results'

logging:
  level: 'INFO'
  save_to_file: true
  log_frequency: 10